CREATE TRIGGER `TG_LOG_SEQUENCES_HISTORY` AFTER UPDATE ON `SEQUENCES` 
FOR EACH ROW INSERT INTO `SEQUENCE_VALUES_HISTORY`(`guid`, `sequence_value`) VALUES (NEW.`last_history_marker`, NEW.`sequence_value`);
/

CREATE FUNCTION `SEQ_NEXT`(`SEQ_NAME` VARCHAR(40)) RETURNS BIGINT(20)
BEGIN
	DECLARE `SQ_HISTORY_MARKER` VARCHAR(36) DEFAULT UUID();
	DECLARE `SQ_VALUE` BIGINT(20) DEFAULT 0;
	UPDATE `SEQUENCES` SET `sequence_value`=`sequence_value`+1, `last_history_marker` = `SQ_HISTORY_MARKER` WHERE `sequence_name`=`SEQ_NAME`;
	SELECT `HISTORY`.`sequence_value` INTO `SQ_VALUE` FROM `SEQUENCE_VALUES_HISTORY` `HISTORY` WHERE `HISTORY`.`guid`= `SQ_HISTORY_MARKER`;
	RETURN (`SQ_VALUE`);
END
/
