<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.bcs.io/fileserver/soap/endpoints/files"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="WSDirectFileAccessServicePort"
	targetNamespace="http://www.bcs.io/fileserver/soap/endpoints/files"
	xmlns:storage="http://www.bcs.io/fileserver/soap/types/file/storage"
	xmlns:global="http://www.bcs.io/fileserver/soap/types/common">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.bcs.io/fileserver/soap/types/file/storage"
				schemaLocation="file-storage-types.xsd">
			</xsd:import>
			<xsd:import
				namespace="http://www.bcs.io/fileserver/soap/types/common"
				schemaLocation="global-types.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getDirectContentPartReferenceRequest">
		<wsdl:part element="storage:GetDirectContentPartReferenceRq"
			name="parameters" />
	</wsdl:message>

	<wsdl:message name="getDirectContentPartReferenceResponse">
		<wsdl:part element="storage:GetDirectContentPartReferenceRs"
			name="parameters" />
	</wsdl:message>


	<wsdl:message name="getDirectContentPartReferenceFault">
		<wsdl:part name="parameters" element="global:ServiceFault" />
	</wsdl:message>
	<wsdl:portType name="WSDirectFileAccessService">
		<wsdl:operation name="getDirectContentPartReference">
			<wsdl:input
				message="tns:getDirectContentPartReferenceRequest" />
			<wsdl:output
				message="tns:getDirectContentPartReferenceResponse" />
			<wsdl:fault name="fault"
				message="tns:getDirectContentPartReferenceFault"></wsdl:fault>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="WSDirectFileAccessServiceBinding"
		type="tns:WSDirectFileAccessService">

		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getDirectContentPartReference">

			<soap:operation
				soapAction="http://www.bcs.io/fileserver/soap/endpoints/files/getDirectContentPartReference" />
			<wsdl:input>

				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">

				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="WSDirectFileAccessServiceEndpoint">
		<wsdl:port binding="tns:WSDirectFileAccessServiceBinding"
			name="WSDirectFileAccessServicePort">
			<soap:address
				location="http://www.bincloud.io/bcs/WSFileService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
