<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.bincloud.io/storage/FileStorageService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FileStorageService"
	targetNamespace="http://www.bincloud.io/storage/FileStorageService"
	xmlns:xsd1="http://www.example.org/file-storage-types"
	xmlns:xsd2="http://www.bincloud.io/storage/file-storage-types/">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.bincloud.io/storage/file-storage-types/"
				schemaLocation="file-storage-types.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="createFileRevisionRequest">
		<wsdl:part name="parameters"
			element="xsd2:CreateFileRevisionRq"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="createFileRevisionResponse">
		<wsdl:part name="parameters"
			element="xsd2:CreateFileRevisionRs"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="FileRevisionManager">
        <wsdl:operation name="createFileRevision">
        	<wsdl:input message="tns:createFileRevisionRequest"></wsdl:input>
        	<wsdl:output message="tns:createFileRevisionResponse"></wsdl:output>
        </wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FileRevisionManagerBinding"
		type="tns:FileRevisionManager">


		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="createFileRevision">

			<soap:operation
				soapAction="http://www.bincloud.io/storage/file-storage-service/createFileRevision" />
			<wsdl:input>

				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="FileStorageService">
		<wsdl:port binding="tns:FileRevisionManagerBinding"
			name="FileRevisionManagerPort">
			<soap:address location="http://www.bincloud.io/storage/FileRevisionManager" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
