<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:tns="http://www.bcs.io/fileserver/api/services/internal"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="bcs-private-services"
	targetNamespace="http://www.bcs.io/fileserver/api/services/internal"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd1="http://www.bcs.io/fileserver/api/types/internal"
	xmlns:global="http://www.bcs.io/global/types">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.bcs.io/fileserver/api/types/internal"
				schemaLocation="bcs-private-services.xsd">
			</xsd:import>
			<xsd:import namespace="http://www.bcs.io/global/types"
				schemaLocation="../xsd/global-types.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getDirectContentUrlRequest">
		<wsdl:part name="parameters"
			element="xsd1:GetDirectContentUrlRq"></wsdl:part>
	</wsdl:message>

	<wsdl:message name="getDirectContentUrlResponse">
		<wsdl:part name="parameters"
			element="xsd1:GetDirectContentUrlRs"></wsdl:part>
	</wsdl:message>

	<wsdl:message name="getDirectContentUrlFault">
		<wsdl:part name="parameters" element="global:ServiceFault"></wsdl:part>
	</wsdl:message>

	<wsdl:portType name="WSContentAccess">
		<wsdl:operation name="getDirectContentUrl">
			<wsdl:input message="tns:getDirectContentUrlRequest"></wsdl:input>
			<wsdl:output message="tns:getDirectContentUrlResponse"></wsdl:output>
			<wsdl:fault name="fault"
				message="tns:getDirectContentUrlFault"></wsdl:fault>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="WSContentAccessBinding"
		type="tns:WSContentAccess">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getDirectContentUrl">
			<soap:operation
				soapAction="http://www.bcs.io/fileserver/api/wsdl/bcs-private-services.wsdl/getDirectContentUrl" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BCSPrivateServicesEndpoint">
		<wsdl:port name="BCSPrivateServicesPort"
			binding="tns:WSContentAccessBinding">
			<soap:address
				location="http://www.bcs.io/fileserver/api/private/BCSPrivateServices" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
